### ISSUE TITLE
Contacts storing

### ISSUE THREAD

**Issue by srrdasa** [dilipkumarvignesh/folkCalling#2] opened 2018-01-04 12:46 UTC
Please find a way to save all the contacts in the phone right from the app

State should check for the number if it is already existing in the phone directory if it is not existing then you should create a contact with the specified name

This should be a separate functionality altogether and not adding please contact one by one before sending message

We should add all the contacts at once and wait for sometime and then run the function for sending message

**Comment by dilipkumarvignesh** [comment] 2018-01-04 16:06
Closing this issue since its not a bug but a new development request. Added requirement in Trello .

**Closed as completed by dilipkumarvignesh** 2018-01-04 16:06 UTC
